# Generated by Django 2.2 on 2019-06-13 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_type',
            fields=[
                ('id_contact_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('validation_regexp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_location', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100, null=True)),
                ('street_name', models.CharField(max_length=100, null=True)),
                ('street_number', models.IntegerField(null=True)),
                ('zip', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id_meeting', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(max_length=100)),
                ('start_time', models.TimeField(max_length=100)),
                ('description', models.CharField(default='', max_length=100, null=True)),
                ('duration', models.DurationField(default=0)),
                ('id_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('birth_day', models.DateField(default='1900-01-01')),
                ('height', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20, null=True)),
                ('id_location', models.ForeignKey(default=52, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Relation_type',
            fields=[
                ('id_relation', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id_relation', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, null=True)),
                ('id_person1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='who1', to='firstapp.Person')),
                ('id_person2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='who2', to='firstapp.Person')),
                ('id_relation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Relation_type')),
            ],
        ),
        migrations.CreateModel(
            name='Person_meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Meeting')),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id_contact', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('id_contact_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.Contact_type')),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.Person')),
            ],
        ),
    ]
